### ISSUE TITLE
Local Target Artifact - Menu Scroll

### ISSUE THREAD

**Issue by jonprow** [lalit2054/yuyutsu#6]
**App Version: 1.1.0**
Platform: win32 10.0.19041
OS: Windows

Unable to scroll further in the target iflow menu

![2021-11-11_9-35-32](https://user-images.githubusercontent.com/35116338/141316194-89f8ae21-3813-4cd9-9038-a83fd1726b77.png)

**Comment by lalit2054** [comment]
@jonprow , I have fixed the bug related to target artifact selector. Kindly update and let me know if you face any issues.
